// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa4JV5MBaDh7rDHqFAWHk_qTz2nDysU7M',
    appId: '1:351059508222:web:72f8e24ffe7ffbdaca9eaf',
    messagingSenderId: '351059508222',
    projectId: 'tourism-cb86f',
    authDomain: 'tourism-cb86f.firebaseapp.com',
    storageBucket: 'tourism-cb86f.appspot.com',
    measurementId: 'G-489C8QMZW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXFPizZgA6lCYGdS_FNdxTdMjLWRoG3C0',
    appId: '1:351059508222:android:aecbafc44dd76bc0ca9eaf',
    messagingSenderId: '351059508222',
    projectId: 'tourism-cb86f',
    storageBucket: 'tourism-cb86f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvb6M_LUjqsXCXW1STZ2cw_2-eLQ9-Gbw',
    appId: '1:351059508222:ios:d865a436c0d76c5fca9eaf',
    messagingSenderId: '351059508222',
    projectId: 'tourism-cb86f',
    storageBucket: 'tourism-cb86f.appspot.com',
    iosBundleId: 'com.mgogolowicz.loginUi',
  );
}
